voxel_size: [0.075, 0.075, 0.2]
point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]

model:
  encoders:
    camera:
      backbone:
        type: InternImage
        core_op : [DCNv3, DCNv3, DCNv3, DCNv3]
        channels: 64
        depths: [4, 4, 18, 4]
        groups: [4, 8, 16, 32]
        mlp_ratio : 4.
        drop_path_rate : 0.2
        norm_layer : LN
        layer_scale : 1.0
        offset_scale : 1.0
        post_norm : False
        with_cp : True 
        out_indices : [1, 2, 3]
        init_cfg:
          type: Pretrained
          checkpoint: https://huggingface.co/OpenGVLab/InternImage/resolve/main/internimage_t_1k_224.pth
      neck:
        in_channels: [128, 256, 512]
      vtransform:
        xbound: [-54.0, 54.0, 0.3]
        ybound: [-54.0, 54.0, 0.3]
        latent_render : True
    lidar:
      voxelize:
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [120000, 160000]
      backbone:
        sparse_shape: [1440, 1440, 41]

  heads:
    object:
      train_cfg:
        grid_size: [1440, 1440, 41]
      test_cfg:
        grid_size: [1440, 1440, 41]

lr_config:
  policy: CosineAnnealing
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.33333333
  min_lr_ratio: 1.0e-3
