voxel_size: [0.075, 0.075, 0.2]
point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]

EfficientFormer_width : [96, 192, 384, 768]

EfficientFormer_depth : [6, 6, 18, 8]

model:
  encoders:
    camera:
      backbone:
        type: EfficientFormer
        layers : [6, 6, 18, 8]
        embed_dims : [96, 192, 384, 768]
        downsamples : [True, True, True, True]
        vit_num : 8
        fork_feat : True
      neck:
        in_channels: [192, 384, 768]
      vtransform:
        xbound: [-54.0, 54.0, 0.3]
        ybound: [-54.0, 54.0, 0.3]
    lidar:
      voxelize:
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [120000, 160000]
      backbone:
        sparse_shape: [1440, 1440, 41]

  heads:
    object:
      train_cfg:
        grid_size: [1440, 1440, 41]
      test_cfg:
        grid_size: [1440, 1440, 41]

lr_config:
  policy: CosineAnnealing
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.33333333
  min_lr_ratio: 1.0e-3
