voxel_size: [0.075, 0.075, 0.2]
point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]

model:
  encoders:
    camera:
      backbone:
        type: ResNet
        depth: 18
        out_indices: [1, 2, 3]
        #init_cfg:
        #  type: Pretrained
        #  checkpoint: https://download.openmmlab.com/pretrain/third_party/resnet18_v1c-b5776b93.pth
      neck:
        in_channels: [512, 1024, 2048]
        #in_channels: [128, 256, 512]
      vtransform:
        in_channels: 256
        out_channels: 80
        image_size: ${image_size}
        feature_size: ${[image_size[0] // 8, image_size[1] // 8]}
        xbound: [-54.0, 54.0, 0.3]
        ybound: [-54.0, 54.0, 0.3]
        zbound: [-10.0, 10.0, 20.0]
        dbound: [1.0, 60.0, 0.5]
        downsample: 2
    lidar:
      voxelize:
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [120000, 160000]
      backbone:
        sparse_shape: [1440, 1440, 41]

  heads:

    object:
      train_cfg:
        grid_size: [1440, 1440, 41]
      test_cfg:
        grid_size: [1440, 1440, 41]

# lr_config:
#   policy: CosineAnnealing
#   warmup: linear
#   warmup_iters: 20000
#   warmup_ratio: 0.33333333
#   min_lr_ratio: 1.0e-3
