voxel_size: [0.075, 0.075, 0.2]
point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]

model:
  encoders:
    camera:
      backbone:
        type: convformer_s36
        init_cfg:
          type: Pretrained
          checkpoint: https://huggingface.co/sail/dl/resolve/main/convformer/convformer_s36.pth
      neck:
        in_channels: [128, 320, 512]
      vtransform:
        xbound: [-54.0, 54.0, 0.3]
        ybound: [-54.0, 54.0, 0.3]
    lidar:
      voxelize:
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [120000, 160000]
      backbone:
        sparse_shape: [1440, 1440, 41]

  heads:
    object:
      train_cfg:
        grid_size: [1440, 1440, 41]
      test_cfg:
        grid_size: [1440, 1440, 41]

# lr_config:
#   policy: CosineAnnealing
#   warmup: linear
#   warmup_iters: 20000
#   warmup_ratio: 0.33333333
#   min_lr_ratio: 1.0e-3
data:
  samples_per_gpu: 4 #4
  workers_per_gpu: 4 #4

lr_config:
   policy: CosineAnnealing
   warmup: linear
   warmup_iters: 500
   warmup_ratio: 0.33333
   min_lr_ratio: 1.0e-3


optimizer:
  type: AdamW
  lr: 2.0e-4
  weight_decay: 0.001

max_epochs: 12